#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Bohdan Puhach

"""Regenerates CRSF test vectors from the protocol definition.

Deliberately an independent implementation: CRC and bit packing are written from the protocol
facts here, so the C++ library is checked against a second implementation rather than itself.
No vectors are taken from any third-party source.

Usage: python3 generate_vectors.py [output_dir]
"""

import random
import sys
from pathlib import Path

SYNC_BYTE = 0xC8
FRAMETYPE_RC_CHANNELS_PACKED = 0x16
CHANNEL_COUNT = 16
CHANNEL_BITS = 11
CHANNEL_MIN = 172
CHANNEL_MID = 992
CHANNEL_MAX = 1811
CRC_POLY = 0xD5


def crc8_dvb_s2(data: bytes) -> int:
    crc = 0
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = ((crc << 1) ^ CRC_POLY) & 0xFF if crc & 0x80 else (crc << 1) & 0xFF
    return crc


def pack_channels(channels: list[int]) -> bytes:
    """Packs channels as a continuous LSB-first bitstream."""
    pending = 0
    pending_bits = 0
    out = bytearray()
    for value in channels:
        pending |= (value & ((1 << CHANNEL_BITS) - 1)) << pending_bits
        pending_bits += CHANNEL_BITS
        while pending_bits >= 8:
            out.append(pending & 0xFF)
            pending >>= 8
            pending_bits -= 8
    if pending_bits:
        out.append(pending & 0xFF)
    return bytes(out)


def build_frame(address: int, frame_type: int, payload: bytes) -> bytes:
    length = len(payload) + 2  # type + crc
    body = bytes([frame_type]) + payload
    return bytes([address, length]) + body + bytes([crc8_dvb_s2(body)])


def rc_channel_cases() -> list[tuple[str, list[int]]]:
    rng = random.Random(20260831)
    cases = [
        ("all_min", [CHANNEL_MIN] * CHANNEL_COUNT),
        ("all_mid", [CHANNEL_MID] * CHANNEL_COUNT),
        ("all_max", [CHANNEL_MAX] * CHANNEL_COUNT),
        ("all_zero", [0] * CHANNEL_COUNT),
        ("all_bits_set", [(1 << CHANNEL_BITS) - 1] * CHANNEL_COUNT),
        ("ramp", [CHANNEL_MIN + i * 109 for i in range(CHANNEL_COUNT)]),
        ("alternating_extremes", [CHANNEL_MIN if i % 2 else CHANNEL_MAX for i in range(CHANNEL_COUNT)]),
        ("failsafe_centered", [CHANNEL_MID] * 4 + [CHANNEL_MIN] * (CHANNEL_COUNT - 4)),
    ]
    for i in range(4):
        cases.append((f"random_{i}", [rng.randrange(0, 1 << CHANNEL_BITS) for _ in range(CHANNEL_COUNT)]))
    return cases


def main() -> int:
    out_dir = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).parent)
    out_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated by generate_vectors.py - do not edit by hand.",
        "# name;channels(comma separated);frame(hex)",
    ]
    for name, channels in rc_channel_cases():
        frame = build_frame(SYNC_BYTE, FRAMETYPE_RC_CHANNELS_PACKED, pack_channels(channels))
        assert len(frame) == 26, f"{name}: unexpected frame size {len(frame)}"
        lines.append(f"{name};{','.join(str(c) for c in channels)};{frame.hex()}")

    (out_dir / "rc_channels.csv").write_text("\n".join(lines) + "\n")
    print(f"wrote {out_dir / 'rc_channels.csv'} ({len(lines) - 2} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
